version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: docker-compose
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: pip # also includes poetry
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm # also includes yarn and pnpm
    directory: "/ui2"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10